# Generated by Django 2.0.4 on 2018-04-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amunt',
            new_name='amount',
        ),
    ]
